---
- name: Provision
  package: 
    name: mariadb-server, MySQL-python
    state: '{{ mariadb.provision | default("present") }}'
  tags: provision

- name: MariaDB is running thru restarts
  service: 
    name: mariadb
    state: started
    enabled: yes
  tags: service

- name: 'Database: {{ mariadb.name }} exists'
  mysql_db:
    name: '{{ mariadb.name }}'
    state: present
  when: mariadb.name is defined
  tags: import_db

- name: 'SQL file: {{ mariadb.import }} transfered to /tmp'
  copy:
    src: '{{ mariadb.import }}'
    dest: '/tmp/{{ mariadb.import }}'
  when:
    - mariadb.import is defined
    - mariadb.name is defined
  tags: import_db

- name: 'Importing /tmp/{{ mariadb.import }} to {{ mariadb.name }}'
  mysql_db:
    name: '{{ mariadb.name }}'
    state: import
    target: '/tmp/{{ mariadb.import }}'
  when:
    - mariadb.import is defined
    - mariadb.name is defined
  tags: import_db
  ignore_errors: True # Not idempotent - so ignoring for now, there is Ansible module related trouble: https://github.com/ansible/ansible/issues/20196

- name: 'GRANT {{ mariadb.name }}{{ mariadb.priv | default(".*:SELECT") }} TO {{ mariadb.user }}'
  mysql_user:
    name: '{{ mariadb.user | default("vagrant") }}'
    priv: '{{ mariadb.name }}{{ mariadb_priv | default(".*:SELECT")}}'
    password: '{{ mariadb.pass | default("vagrant") }}'
  when: mariadb.name is defined
  tags: rights
